### ISSUE TITLE
j may be used unitialized

### ISSUE THREAD

**Issue by Gregwar** [RemiFabre/WorldDomination#1]
https://github.com/RemiFabre/WorldDomination/blob/213ca83c1590b52376bf634b3eb61ff7f374aefb/firmware/main.c#L3

**Comment by RemiFabre** [comment]
Part of the plan

**Comment by Gregwar** [comment]
Moreover, you should use a bigger neural network, just one 1x1 fully connected layer with no activation fonction is a little bit light
